name: 最强APK反编译
on:
  workflow_dispatch:
    inputs:
      url:
        description: 输入 transfer.sh / file.io 公开直链
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 下载真实APK
        run: |
          wget -O target.apk "${{ github.event.inputs.url }}"
          ls -lh target.apk  # 必须显示 几百MB

      - name: 下载反编译工具
        run: |
          wget -O jadx.zip https://github.com/skylot/jadx/releases/download/v1.5.3/jadx-1.5.3.zip
          unzip -q jadx.zip

      - name: 开始逆向！
        run: jadx/bin/jadx --export-gradle -d out target.apk

      - name: 获取源码
        uses: actions/upload-artifact@v4
        with:
          name: 逆向完成-源码
          path: out/
